name: Run Tests

on:
  push:

permissions:
  contents: write

env:
  OPENAI_API_KEY: fake-api-key

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: |
          sudo apt-get update &&
          pip install poetry &&
          poetry lock &&
          poetry install

      - name: Run tests
        uses: koenhagen/measure-energy-action@v0.33
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: poetry run pytest
          count: 30